# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Grid2Tif
                                 A QGIS plugin
 Grid export to tif
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-11
        copyright            : (C) 2019 by Milickij Alex
        email                : milickij@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Grid2Tif class from file Grid2Tif.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .export_tif import Grid2Tif
    return Grid2Tif(iface)
